<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    public function friends() {
        return $this->belongsToMany(User::class, 'friends', 'user_id1', 'user_id2');
    }

    public function myReceivedMessages() {
        return $this->hasMany(Message::class, 'user_id_recipient');
    }

    public function mySentMessages() {
        return $this->hasMany(Message::class, 'user_id_sender');
    }

    public function myReceivedImages() {
        return $this->hasMany(Image::class, 'user_id_recipient');
    }

    public function mySentImages()  {
        return $this->hasMany(Image::class, 'user_id_sender');
    }

    public function likes() {
        return $this->belongsToMany(Message::class, 'likes', 'user_id','post_id');
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'password', 'email', 'number', 'first_name', 'last_name', 'third_name', 'country', 'city', 'filename', 'admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getRouteKeyName()
    {
        return 'name'; // TODO: Change the autogenerated stub
    }
}
